# .github/workflows/android-ci.yml

name: Android CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the Java Development Kit (JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Grants execute permissions to the Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Runs the Gradle build task
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Uploads the generated APK as a build artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
